### ISSUE TITLE
Feature Request: Clean 'unsafe' characters from output file names

### ISSUE THREAD

**Issue by GorramRob** [hellt/cmdo#16]
When running commands and storing the output in the files, there are characters in the file names that are safe for Linux systems but they cannot be transferred to some other OS hosts without renaming all the files with output from that particular command with the offending characters. Perhaps an additional switch could be added to make the output file names safe (since you do lose some information this way.)

The approach I was taking was convert anything in the character class [^\w\-_] and change it to an _ character. Then do a second pass to remove any contiguous [\-_] characters and replace them with a single hyphen or underscore (which ever came first.)

**Comment by hellt** [comment]
Hi. Can you give me an example of such a file name?

**Comment by GorramRob** [comment]
Certainly - one I just created is:
`'-show-router-interface-|-match-ignore-case-to.*up.*1--expression'`

Some of the characters that aren't allowed in windows are:
* \* (asterisk)
* < (less than)
* \> (greater than)
* : (colon - sometimes works, but is actually NTFS Alternate Data Streams)
* " (double quote)
* / (forward slash)
* \ (backslash)
* | (vertical bar or pipe)
* ? (question mark)

There could be more? This is the range that I usually use for file naming in windows to be considered "safe":
* Letters (a-z A-Z) - Unicode characters as well, if needed
* Digits (0-9)
* Underscore (_)
* Hyphen (-)
* Space
* Dot (.)

**Comment by hellt** [comment]
Hi @GorramRob 
sorry it took me so long, but in today news 0.6.5 version contains the sanitizing rules which should work both on win and linux filesystems
