### ISSUE TITLE
Spaces in Filenames

### ISSUE THREAD

**Issue by servidge** [hellt/cmdo#23]
I hope this project is still alive. I installed the latest version using the install script. 
It works quite well on a recent Debian with Cisco IOS components. 
However, I have two anomalies that may be related. 
There are differences in the generated filenames of the individual commands compared to the asciinema recording. 
The filenames contain spaces, which makes further scripts annoyingly complicated.
I haven't found anything while browsing the code, but is there a switch to replace the spaces with - or some other character?
It feels like the one in ' Sanitise filenames #20 ' got lost somewhere between the regex and the NewReplacer?

Additional questions or possible additions
Is there a switch that can affect the number of concurrent connections?
Is there something like send-commands-from-file for devices or addresses?

**Comment by hellt** [comment]
There is very little attention to cmdo from my side at this time, since there are other priorities. Maybe someone could chime in and see whats going on until I have spare cycles

**Comment by servidge** [comment]
Thanks for the quick reply and no problem. 
I quickly solved it with a bash script. Code: `for f in outputs/*/*; do mv "$f" "${f// /_}"; done`
And the go code doesn't look that complicated. Maybe I can find some time and fix it myself.

**Comment by hellt** [comment]
thanks for the contribution. It is now live with 0.7.0 version

**Comment by servidge** [comment]
Thank you and sorry that there was a problem with the pipeline which resulted in more work.
